config/routes.rb
StartupShopKC::Application.routes.draw do
  get 'home/index', as: 'home'
  root :to => 'home#index'
  
  get 'search'          => 'home#search', as: 'search'
  post 'search'         => 'home#search', as: 'search'
  get 'update_map'      => 'home#update_map'
  get 'signin'          => 'sessions#new', as: 'signin'
  post 'signin'         => 'sessions#create'
  get 'signout'         => 'sessions#destroy'
  get 'signup'          => 'users#new', as: 'signup'
  get 'my_account'      => 'users#my_account', as: 'my_account'
  get 'charge'          => 'users#charge'
  post 'update_card'    => 'users#update_card'
  get 'locations_by_category' => 'locations#locations_by_category'
  match 'confirm_email/:code' => 'users#confirm_email'
  
  match 'auth/:provider/callback', to: 'sessions#provider'
  match 'auth/failure', to: redirect('/')

  resources :users
  resources :locations
  resources :events
  
  namespace :admin do
    get 'dashboard/index'
    get 'first_admin' => 'dashboard#first_admin', as: 'first_admin'
    post 'create_first_admin' => 'dashboard#create_first_admin', as: 'create_first_admin'
    put 'update_user' => 'dashboard#update_user', as: 'update_user'
    get 'active_location' => 'dashboard#active_location'
    get 'location_filter' => 'dashboard#location_filter'
    get 'active_event' => 'dashboard#active_event'
    get 'event_filter' => 'dashboard#event_filter'
    get 'remove_twitter' => 'dashboard#remove_twitter'
    post 'update_cost' => 'dashboard#update_cost'
    post 'update_twitter' => 'dashboard#update_twitter'
    post 'import_locations' => 'dashboard#import_locations', as: 'import_locations'
    match "/" => "dashboard#index"
    root :to => "admin/dashboard#index"
  end
  
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_filter :authenticate_admin, except: [:first_admin, :create_first_admin]
  layout 'admin'
  
  def active_location
    @location = Location.find params[:id]
    active = !@location.active
    @location.update_attributes(active: active)
    respond_to :js
  end
  
  def active_event
    @event = Event.find params[:id]
    active = !@event.active
    @event.update_attributes(active: active)
    respond_to :js
  end
  
  def location_filter
    status = params[:status]
    @locations = Location.actived_list if status=='active'
    @locations = Location.unactived_list if status=='unactive'
    respond_to :js
  end
  
  def event_filter
    status = params[:status]
    @events = Event.actived_list if status=='active'
    @events = Event.unactived_list if status=='unactive'
    respond_to :js
  end
  
  def import_locations
    success_count = 0
    fails_count = 0
    uploader = FileUploader.new
    begin
      require 'csv'
      
      random = (0...8).map{65.+(rand(25)).chr}.join
      params[:file].original_filename = "#{random}_#{params[:file].original_filename}" 
      uploader.store!(params[:file])

      csv_text = File.read(uploader.path, { encoding: "UTF-8" })
      
      csv = CSV.parse(csv_text, :headers => true)
      
      csv.each do |row|
        @location = Location.new
        @location.name = row[0]
        @location.description = row[1]
        @location.address = row[2]
        @location.phone = row[3]
        @location.email = row[4]
        @location.url = row[5]
        @location.twitter = row[6]
        @location.facebook = row[7]
        @location.active = row[8].blank? ? false : (row[8].downcase=='true' ? true : false)
        @location.paid = row[9].blank? ? false : (row[9].downcase=='true' ? true : false)
        @location.logo = row[10] unless row[10].blank?
        
        user = User.where(username: row[11]).first
        user = current_user unless user
        
        @location.user_id = user.id
        @location.category = row[12]
        @location.sub_category = row[13]
        
        if(check_row(row))
          @location.save
          if @location.errors.blank?
            success_count += 1
          else
            fails_count += 1
            puts @location.errors.full_messages
            flash[:alert] = @location.errors.full_messages.first
          end
        else
          fails_count += 1
        end
      end
      uploader.remove!
    rescue Exception => e
      flash[:alert] = e.message
      uploader.remove!
    end
    
    flash[:notice] = "#{success_count} imported, #{fails_count} fails"
    redirect_to '/admin'
  end
  
  def index
    init
    @user = current_user
    @show_tab = '1'
    @show_tab = params[:tab] unless params[:tab].blank?
  end
  
  def first_admin
    unless first_access
      redirect_to '/signin'
    else
      @user = User.new
    end
  end
  
  def create_first_admin
    unless first_access
      redirect_to '/signin'
    else
      @errors = []
      @user = User.new params[:user]
      @errors << "password confirmation is not matched" if params[:user][:password] != params[:password_confirmation]
     
      if @errors.blank?
        @user.role = "admin"
        if @user.save
          flash[:notice] = 'Create Admin successful'
          redirect_to '/signin'
        else
          @errors = @user.errors.full_messages
          render :first_admin
        end
      else
        render :first_admin
      end
    end
  end
  
  def remove_twitter
    @name = params[:name]
    t_accounts = Setting.where(name: 'twitters').first
    t_arr = t_accounts.svalue.split(',')
    t_arr -= [@name]
    t_accounts.update_attributes(svalue: t_arr.join(','))
    
    respond_to :js
  end
  
  def update_cost
    @cost = params[:cost]
    setting_cost = Setting.where(name: 'up_cost').first
    setting_cost.update_attributes(value: @cost)
    respond_to :js
  end
  
  def update_twitter
    @name = params[:name]
    t_accounts = Setting.where(name: 'twitters').first
    t_arr = t_accounts.svalue.split(',')
    @errors =[]
    if t_arr.include?(@name)
      @errors << "name already in list"
    else
     begin
      Twitter.user_timeline(@name)
     rescue
      @errors << "Twitter name invalid"
     end
    end
    if @errors.blank?
      t_arr << @name
      t_accounts.update_attributes(svalue: t_arr.join(','))
    end
    
    respond_to :js
  end
  
  def update_user
    @errors = []
    unless params[:user][:password].blank? && params[:password_confirmation].blank?
      @errors << "password confirmation is not matched" if params[:user][:password] != params[:password_confirmation]
    else
      params[:user].delete(:password)
    end
    @user = User.find params[:id]
    @show_tab = @user.id == current_user.id ? '1' : '2'
    if @errors.blank?
      @user.update_attributes(params[:user])
      if @user.errors.blank?
        flash[:notice] = "update successful!"
        redirect_to '/admin'
      else
        @display_form = true
        @errors = @user.errors.full_messages
        init
        render :index
      end
    else
      @display_form = true
      init
      render :index
    end
  end
  
  private
  
    def init
      @users = User.all
      @locations = Location.all
      @events = Event.all
      setting_cost = Setting.where(name: 'up_cost').first
      setting_cost = Setting.create(name: 'up_cost', value: 1.00) unless setting_cost
      @upgrade_cost = setting_cost.value
      t_accounts = Setting.where(name: 'twitters').first
      t_accounts = Setting.create(name: 'twitters', svalue: '') unless t_accounts
      @t_accounts = t_accounts.svalue.split(',')
      @registed_users = User.where(role: 'user')
      @confirmed_users = User.where(role: 'user', confirm_code: 'confirmed')
      
      @actived_locations = Location.actived_list
      @unactived_locations = Location.unactived_list
      @actived_events = Event.actived_list
      @unactived_events = Event.unactived_list
    end
    
    def check_valid_address address
      addr = Geokit::Geocoders::GoogleGeocoder.geocode(address)
      if addr.success
        @location.latitude = addr.lat
        @location.longitude = addr.lng
        return true
      else
        return false
      end
    end
    
    def check_row row
      return false if (row[0].blank? || row[2].blank? || row[3].blank? || row[4].blank?)
      return false if (row[0]=='n/a' || row[2]=='n/a' || row[3]=='n/a' || row[4]=='n/a')
      return false unless check_valid_address(row[2])
      return true
    end
end

app/views/admin/dashboard/_active_event.html.haml
- if event.active
  = link_to 'Deactive', admin_active_event_path(id: event.id), remote: true, class: 'waiting'
- else
  = link_to 'Active', admin_active_event_path(id: event.id), remote: true, class: 'waiting'

app/views/admin/dashboard/_events.html.haml
.span12.no-lmargin
  %p
    %h2 Events
%br
%p
  = link_to 'actived events', admin_event_filter_path(status: 'active'), class: 'waiting', remote: true
  |
  = link_to 'unactived events', admin_event_filter_path(status: 'unactive'), class: 'waiting', remote: true
.span12.no-lmargin.notice= notice
.span12.no-lmargin.shadow_box{style: "width: 1140px;"}
  .span12.no-lmargin
    .span2.no-lmargin.th
      Name
    .span3.no-lmargin.th
      Description
    .span3.no-lmargin.th
      Address
    .span2.no-lmargin.th
      User
    .span1.no-lmargin.th
      Activate
    .span1.no-lmargin.th
      &nbsp;
  #event_table
    = render partial: 'event_table'
:javascript
  $(document).ready(function(){
    $("a.waiting").live('click', function(){
      $("#fading-image").show();
    });
    
  });

app/views/admin/dashboard/_location_table.html.haml
- bg_class = 'even'
- @locations.each do |location|
  - bg_class = bg_class == 'odd' ? 'even' : 'odd'
  .span13.no-lmargin{id: "loc_row_#{location.id}"}
    .span2.no-lmargin{class: "#{bg_class}"}
      = location.name
    .span3.no-lmargin{class: "#{bg_class}"}
      = location.description
      &nbsp;
    .span3.no-lmargin{class: "#{bg_class}"}
      = location.address
    .span2.no-lmargin{class: "#{bg_class}"}
      = location.user.username
    .span1.no-lmargin{class: "#{bg_class}", id: "act_text_#{location.id}"}
      = location.active?
    .span1.no-lmargin{class: "#{bg_class}", id: "act_ctrl_#{location.id}"}
      = render partial: "active_location", locals: {location: location}
    .span1.no-lmargin{class: "#{bg_class}"}
      = link_to 'delete', location_path(location), method: 'delete', remote: true, class: "delete"

:javascript
  $("a.delete").click(function(){
    $("#fading-image").show();
  });

app/views/admin/dashboard/_locations.html.haml
.span12.no-lmargin
  %h2 Import Loctions from file
  ~ form_tag admin_import_locations_path, multipart: true do
    .span10.no-lmargin
      .span1 CSV file
      .span6= file_field_tag :file, size: '13'
    .span10.no-lmargin= submit_tag "Upload"
.span12.no-lmargin
  %p
    %h2 Locations
%br
%p
  = link_to 'actived locations', admin_location_filter_path(status: 'active'), class: 'waiting', remote: true
  |
  = link_to 'unactived locations', admin_location_filter_path(status: 'unactive'), class: 'waiting', remote: true
.span13.no-lmargin.shadow_box{style: "width: 1230px;"}
  .span13.no-lmargin
    .span2.no-lmargin.th
      Name
    .span3.no-lmargin.th
      Description
    .span3.no-lmargin.th
      Address
    .span2.no-lmargin.th
      User
    .span1.no-lmargin.th
      Activate
    .span1.no-lmargin.th
      &nbsp;
    .span1.no-lmargin.th
      &nbsp;
  #location_table
    = render partial: 'location_table'
:javascript
  $(document).ready(function(){
  
    $("a.waiting").live('click', function(){
      $("#fading-image").show();
    });
    
  });

app/views/admin/dashboard/_my_account.html.haml
.span9.no-lmargin
  %p
    %h2 Account Infomation
.span9.no-lmargin.notice= notice
.span9
  .span9.no-lmargin
    .span1.no-lmargin
      Email
    .span7.no-lmargin
      = current_user.username
  .span9.no-lmargin
    .span1.no-lmargin
      Password
    .span7.no-lmargin
      ********
  .span9.no-lmargin{style: "margin-top: 10px;"}
    %p= link_to 'edit', '#edit_account'
  #edit_account.span9.no-lmargin{class: "#{@display_form==true ? '' : 'hidden'}"}
    ~ form_for @user, url: admin_update_user_path(id: @user.id) do |f|
      .errors.span12{style: "margin-bottom: 20px"}
        = render partial: "shared/errors"
      .field.span12
        .span1
          %label Email
        .span4= f.email_field :username
      .field.span12
        .span1
          %label New Password
        .span4= f.password_field :password
      .field.span12
        .span1
          %label Password Confirmation
        .span4= password_field_tag :password_confirmation
      .field.span12
        .span1= submit_tag 'Update'
:javascript
  $(document).ready(function(){
    
    $("a[href=#edit_account]").click(function(e){
      $("#edit_account").toggleClass("hidden");
      text = $(this).html();
      if(text=='edit'){
        text = 'hide form';
      }else{
        text = 'edit';
      }
      $(this).html(text);
      return false;
    });
    
  });

app/views/admin/dashboard/_twitter_row.html.haml
.span4.no-lmargin{id: "twitter_#{name}"}
  .span3.no-lmargin= name
  .span1.no-lmargin= link_to 'remove', admin_remove_twitter_path(name: name), class: 'waiting', remote: true

app/views/admin/dashboard/active_event.js.haml
$("#act_text_#{@event.id}").html("#{@event.active?}");
$("#act_ctrl_#{@event.id}").html("#{escape_javascript(render partial: 'active_event', locals: {event: @event})}");
$("#fading-image").hide();

app/views/admin/dashboard/active_location.js.haml
$("#act_text_#{@location.id}").html("#{@location.active?}");
$("#act_ctrl_#{@location.id}").html("#{escape_javascript(render partial: 'active_location', locals: {location: @location})}");
$("#fading-image").hide();

app/views/admin/dashboard/event_filter.js.haml
$("#event_table").html("#{escape_javascript(render partial: 'event_table')}");
$("#fading-image").hide();

app/views/admin/dashboard/first_admin.html.haml
.span
  %p
    %h2 Create an admin for your site
  %br
  ~ form_for @user, url: admin_create_first_admin_path do |f|
    .errors.span12{style: "margin-bottom: 20px"}
      = render partial: "/shared/errors"
    .field.span12
      .span1
        %label Email
      .span4= f.email_field :username
    .field.span12
      .span1
        %label Password
      .span4= f.password_field :password
    .field.span12
      .span1
        %label Password Confirmation
      .span4= password_field_tag :password_confirmation
    .field.span12
      .span1= submit_tag 'Create'

app/views/admin/dashboard/index.html.haml
#tab_1{class: "#{'hidden' if @show_tab != '1'}"}
  = render partial: "index"
#tab_2{class: "#{'hidden' if @show_tab != '2'}"}
  = render partial: "users"
#tab_3{class: "#{'hidden' if @show_tab != '3'}"}
  = render partial: "locations"
#tab_4{class: "#{'hidden' if @show_tab != '4'}"}
  = render partial: "events"
  
:javascript
  $(document).ready(function(){
    $('a.tabable').live('click', function(){
      var currentTab = $(this).attr('href');
      $("div[id*=tab_]").addClass('hidden');  
      $(currentTab).removeClass('hidden');
      return false;
    });
  });

app/views/admin/dashboard/remove_twitter.js.haml
$("#twitter_#{@name}").fadeOut();
$("#fading-image").hide();

app/views/admin/dashboard/update_cost.js.haml
$("#edit_cost").addClass('hidden');
$("#cost_value").html("#{number_to_currency(@cost)}");
$("a[href=#edit_cost]").html("edit");
$("#fading-image").hide();

app/views/admin/dashboard/update_twitter.js.haml
- if @errors.any?
  $('#add_twitter .errors').html("#{escape_javascript(render partial: 'shared/errors')}");
- else
  $('#add_twitter .errors').html('');
  $('#no_account').html('');
  $('#twitter_names').append("#{escape_javascript(render partial: 'twitter_row', locals: {name: @name})}");
$("#fading-image").hide();