config/routes.rb
StartupShopKC::Application.routes.draw do
  get 'home/index', as: 'home'
  root :to => 'home#index'
  
  get 'search'          => 'home#search', as: 'search'
  post 'search'         => 'home#search', as: 'search'
  get 'update_map'      => 'home#update_map'
  get 'signin'          => 'sessions#new', as: 'signin'
  post 'signin'         => 'sessions#create'
  get 'signout'         => 'sessions#destroy'
  get 'signup'          => 'users#new', as: 'signup'
  get 'my_account'      => 'users#my_account', as: 'my_account'
  get 'charge'          => 'users#charge'
  post 'update_card'    => 'users#update_card'
  get 'locations_by_category' => 'locations#locations_by_category'
  match 'confirm_email/:code' => 'users#confirm_email'
  
  match 'auth/:provider/callback', to: 'sessions#provider'
  match 'auth/failure', to: redirect('/')

  resources :users
  resources :locations
  resources :events
  
  namespace :admin do
    get 'dashboard/index'
    get 'first_admin' => 'dashboard#first_admin', as: 'first_admin'
    post 'create_first_admin' => 'dashboard#create_first_admin', as: 'create_first_admin'
    put 'update_user' => 'dashboard#update_user', as: 'update_user'
    get 'active_location' => 'dashboard#active_location'
    get 'location_filter' => 'dashboard#location_filter'
    get 'active_event' => 'dashboard#active_event'
    get 'event_filter' => 'dashboard#event_filter'
    get 'remove_twitter' => 'dashboard#remove_twitter'
    post 'update_cost' => 'dashboard#update_cost'
    post 'update_twitter' => 'dashboard#update_twitter'
    post 'import_locations' => 'dashboard#import_locations', as: 'import_locations'
    match "/" => "dashboard#index"
    root :to => "admin/dashboard#index"
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # fields :role, :confirm_code, :customer_id
  attr_accessible :username, :password, :password_confirmation, :role, :confirm_code, :customer_id
  has_secure_password
  

  
  def admin?
    return self.role=='admin'
  end
  
  def confirmed?
    return self.confirm_code=='confirmed'
  end
  
  def events
    Event.where(user_id: self.id)
  end
  
  def locations
    Location.where(user_id: self.id)
  end  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user, only: [:my_account]
  
  def confirm_email
    confirm_url = "http://#{request.host_with_port}/confirm_email/#{params[:code]}"
    user = User.where(confirm_code: confirm_url).first
    if user
      user.update_attributes(confirm_code: 'confirmed')
      redirect_to '/', notice: 'Your email has been confirm successfully'
    else
      redirect_to '/', notice: 'Confirm code wrong or it has been used'
    end
  end
  
  def create
    @errors = []
    @user = User.new params[:user]
    if(User.where(username: params[:user][:username]).any?)
      @errors << 'Email has already been taken.'
    end
    @errors << "password confirmation is not matched" if params[:user][:password] != params[:password_confirmation]
   
    if @errors.blank?
      @user.role = "user"
      confirm_code = Digest::SHA1.hexdigest([Time.now, rand].join)
      confirm_url = "http://#{request.host_with_port}/confirm_email/#{confirm_code}"
      @user.confirm_code = confirm_url
      if @user.save
        ConfirmMailer.email_confirm(@user.username, confirm_url).deliver
        flash[:notice] = 'Thank you for registering. A confirmation email was send to you.'
      else
        @errors = @user.errors.full_messages
      end
    end
    respond_to :js
  end
  
  def my_account
    init_card
    @user = current_user
    @locations = @user.locations
    @events = @user.events
  end
  
  def new
    @user = User.new
  end
  
  def charge
    @location = Location.find params[:location]
    redirect_to my_account if @location.paid==true
    # amount in cents
    setting_cost = Setting.where(name: 'up_cost').first
    amount = setting_cost ? setting_cost.value*100 : 100
    @errors = []
    begin
      stripe = YAML.load_file("#{Rails.root}/config/stripe.yml")[Rails.env]
      Stripe.api_key = stripe['secretkey']
      @charge = Stripe::Charge.create(
       :amount => amount.to_i,
       :currency => "usd",
       :customer => current_user.customer_id,
       :description => "payment by #{current_user.username}"
      )
      @location.update_attributes(paid: true)
      flash[:notice] = "successfull charge"
    rescue Exception => e
      @error = e
      @user = current_user
      @locations = @user.locations
      init_card
      render :my_account
      return
    end
    redirect_to my_account_path  
  end
  
  def update_card
    init_card
    @card_errors=[] 
    begin
      if @customer
        @customer.card = params[:card][:token]
        @customer.save
      else
        token = params[:card][:token]
        @customer = Stripe::Customer.create(
          card: token,
          description: "#{current_user.username}"
        )
        current_user.update_attributes(customer_id: @customer.id)
      end
    rescue Exception => e
      @card_errors << e
      render :my_account
      return
    end
    
    @active_card = @customer.active_card
    @card_errors << 'cvc is not accepted' if @active_card.cvc_check == 'fail'
    @card_errors << 'line 1 address is not matched' if @active_card.address_line1_check == 'fail'
    @card_errors << 'zip code is not matched' if @active_card.address_zip_check == 'fail'
    
    if @card_errors.any?
      render :my_account
    else
      redirect_to my_account_path
    end
  end
  
  private
  
    def init_card
      stripe = YAML.load_file("#{Rails.root}/config/stripe.yml")[Rails.env]
      Stripe.api_key = stripe['secretkey']
      customer_id = current_user.customer_id
      begin
        @customer = Stripe::Customer.retrieve(customer_id) if(customer_id)
      rescue Exception => e
        puts e
      end
      
      @active_card = @customer.active_card if @customer
    end
    
end

app/views/users/_card.html.haml
.span12.no-lmargin
  - if @active_card && @card_errors.blank?
    .span9.no-lmargin
      .span2.no-lmargin Name on Card
      .span7.no-lmargin= @active_card.name
    .span9.no-lmargin
      .span2.no-lmargin Card Type
      .span7.no-lmargin= @active_card.type
    .span9.no-lmargin
      .span2.no-lmargin Card Number
      .span7.no-lmargin= "xxxx-xxxx-xxxx-#{@active_card.last4}"
    .span9.no-lmargin
      .span2.no-lmargin Expiration Date
      .span7.no-lmargin= "#{@active_card.exp_year} / #{@active_card.exp_month}"
    .span9.no-lmargin
      %p= link_to 'edit card', '#card_form'
    %br
  #card_form.span9{class: "#{'hidden' if(@active_card && @card_errors.blank?)}"}
    ~ form_tag update_card_path do
      #card_error.span9.no-lmargin{style: "color: red;"}
        - unless @card_errors.blank?
          - @card_errors.each do |msg|
            = msg
            %br
      .span9.no-lmargin
        .span2.no-lmargin
          %label{for: 'first_name'}Name on card
        .span7.no-lmargin
          = text_field_tag '', "#{@active_card.name if @active_card}", class: 'name'
      .span9.no-lmargin
        .span2.no-lmargin
          %label{for: 'number'}Number
        .span7.no-lmargin
          = text_field_tag '', "#{('xxxx-xxxx-xxxx-' + @active_card.last4) if @active_card}", class: 'card-number'
      .span9.no-lmargin
        .span2.no-lmargin
          %label{for: 'type'}Type
        .span7.no-lmargin
          = select_tag '', options_for_select(["Visa","MasterCard","American Express","JCB","Diners Club","Discover"], "#{@active_card.type if @active_card}"), class: 'card-type'
      .span9.no-lmargin
        .span2.no-lmargin
          %label Expiration Date
        .span7.no-lmargin
          %span{style: "width: 100px; float: left;"}
            %div= select_year((@active_card.exp_year if @active_card) || Date.today, start_year: Time.now.year, end_year: Time.now.year + 95)
          %span{style: "width: 100px; float: left;"}
            %div= select_month((@active_card.exp_month if @active_card) || 1, use_month_numbers: true)
      .span9.no-lmargin
        .span2.no-lmargin
          %label{for: 'cvc'}CVC
        .span7.no-lmargin
          = text_field_tag '', '', class: 'card-cvc'
      .span9.no-lmargin
        .span2.no-lmargin
          %label{for: 'address'}Address
        .span7.no-lmargin
          = text_field_tag '', "#{@active_card.address_line1 if @active_card}", class: 'address-line1'
      .span9.no-lmargin
        .span2.no-lmargin
          %label{for: 'address'}Address
        .span7.no-lmargin
          = text_field_tag '', "#{@active_card.address_line2 if @active_card}", class: 'address-line2'
      .span9.no-lmargin
        .span2.no-lmargin
          %label{for: 'state'}State
        .span7.no-lmargin
          = text_field_tag '', "#{@active_card.address_state if @active_card}", class: 'state'
      .span9.no-lmargin
        .span2.no-lmargin
          %label{for: 'zip'}Zip
        .span7.no-lmargin
          = text_field_tag '', "#{@active_card.address_zip if @active_card}", class: 'zip'
      .span9.no-lmargin.submit
        .span9.no-lmargin.submit
          = submit_tag :save
- stripe = YAML.load_file("#{Rails.root}/config/stripe.yml")[Rails.env]
= javascript_include_tag "https://js.stripe.com/v1/"
:javascript
  Stripe.setPublishableKey("#{stripe['publishablekey']}");
  $(document).ready(function(){
    $("a[href=#card_form]").click(function(e){
      $("#card_form").toggleClass("hidden");
      text = $(this).html();
      if(text=='edit card'){
        text = 'hide form';
      }else{
        text = 'edit card';
      }
      $(this).html(text);
      return false;
    });
    //payment
    $("#card_form form").submit(function(event) {
      // disable the submit button to prevent repeated clicks
      $('#card_form input[type=submit]').attr("disabled", "disabled");
      $("#fading-image").show();
      Stripe.createToken({
          name: $('.name').val(),
          number: $('.card-number').val(),
          type: $('.card-type').val(),
          city: $('.city').val(),
          cvc: $('.card-cvc').val(),
          exp_month: $('#date_month').val(),
          exp_year: $('#date_year').val(),
          address_line1: $('.address-line1').val(),
          address_line2: $('.address-line2').val(),
          address_state: $('.state').val(),
          address_zip: $('.zip').val()
      }, stripeResponseHandler);
      // prevent the form from submitting with the default action
      event.preventDefault();
    });

    function stripeResponseHandler(status, response) {
      $("#fading-image").hide();
      if (response.error){
          $("#card_error").text(response.error.message);
          $('#card_form input[type=submit]').removeAttr("disabled");
      } else {
          var form$ = $("#card_form form");
          var token = response['id'];
          form$.append("<input type='hidden' name='card[token]' value='" + token + "'/>");
          form$.get(0).submit();
      }
    }
  });

app/views/users/_events.html.haml
.span12
  %p
    %h2 My Events
- if @error
  .span12
    %p=@error
.span12.shadow_box{style: "width: 1140px;"}
  .span12.no-lmargin
    .span2.no-lmargin.th
      Name
    .span2.no-lmargin.th
      Event Time
    .span2.no-lmargin.th
      Recurring
    .span3.no-lmargin.th
      Address/Company
    .span3.no-lmargin.th
      Description
  - bg_class = 'even'
  - @events.each do |event|
    - bg_class = bg_class == 'odd' ? 'even' : 'odd'
    .span12.no-lmargin
      .span2.no-lmargin{class: "#{bg_class}"}
        = link_to event.name, "#event_#{event.id}", class: "fancybox"
      .span2.no-lmargin{class: "#{bg_class}"}
        = event.e_time
      .span2.no-lmargin{class: "#{bg_class}"}
        = event.recurring
      .span3.no-lmargin{class: "#{bg_class}"}
        = event.address || "[#{event.company.name}] #{event.company.address}"
      .span3.no-lmargin{class: "#{bg_class}"}
        = event.description
        &nbsp;

.hidden
  - @events.each do |event|
    %div{id: "event_#{event.id}"}
      .popover
        .background
          .title
            %span.add-title Edit Event
          .inside        
            = render partial: 'events/form', locals: {event: event}
            %button(href="#event_#{event.id}" class="continue submit") Save

app/views/users/_locations.html.haml
.span12
  %p
    %h2 My Locations
- if @error
  .span12
    %p=@error
.span12.shadow_box{style: "width: 1140px;"}
  .span12.no-lmargin
    .span2.no-lmargin.th
      Name
    .span3.no-lmargin.th
      Description
    .span3.no-lmargin.th
      Address
    .span2.no-lmargin.th
      Email
    .span1.no-lmargin.th
      Activate
    .span1.no-lmargin.th
      Payment
  - bg_class = 'even'
  - @locations.each do |location|
    - bg_class = bg_class == 'odd' ? 'even' : 'odd'
    .span12.no-lmargin
      .span2.no-lmargin{class: "#{bg_class}"}
        = link_to location.name, "#loc_#{location.id}", class: "fancybox"
      .span3.no-lmargin{class: "#{bg_class}"}
        = location.description
        &nbsp;
      .span3.no-lmargin{class: "#{bg_class}"}
        = location.address
      .span2.no-lmargin{class: "#{bg_class}"}
        = location.email
      .span1.no-lmargin{class: "#{bg_class}", id: "act_text_#{location.id}"}
        = location.active?
      .span1.no-lmargin{class: "#{bg_class}"}
        - if location.paid
          Paid
        - else
          = link_to 'Purchase', charge_path(location: location.id) 

.hidden
  - @locations.each do |location|
    %div{id: "loc_#{location.id}"}
      .popover
        .background
          .title
            %span.add-title Edit Location
          .inside        
            = render partial: 'locations/form', locals: {location: location}
            %button(href="#loc_#{location.id}" class="continue submit") Save

app/views/users/_signup.html.haml
- user = @user || User.new
~ form_for user, html: {class: 'form'}, remote: true do |f|
  .input.errors
  .input
    .label
      %i.icon-envelope.form-icon
      Email
    .field
      = f.text_field :username, class: 'text-input required'
  .input
    .label
      %i.icon-key.form-icon
      Password
    .field
      = f.password_field :password, class: 'text-input required'
  .input
    .label
      %i.icon-key.form-icon
      Password Comfirmation
    .field
      = password_field_tag :password_confirmation, '', class: 'text-input required'
  .input
    %button(href="#signup" class="continue") Submit

app/views/users/create.js.haml
- if @errors.blank?
  location.reload();
- else
  $("#popover_signup .errors").html("#{escape_javascript(render partial: 'shared/errors')}")

app/views/users/my_account.html.haml
.span12
  %p
    %h2 My Account
.span12
  .span9.no-lmargin
    .span1.no-lmargin
      Email
    .span8.no-lmargin
      = current_user.username
    
.span12
  %p 
    %h3 Card info
  = render partial: 'card'

= render partial: "locations"  
= render partial: "events"

:javascript
  $(document).ready(function() {
    $("a.fancybox").fancybox({
      autoSize : true
    });
  });
   
  $("button.submit").click(function(){
    element = $(this).attr("href");
    if(validate_fields(element)==true){
      $.fancybox.close();
      $("#fading-image").show();
      $(element + " form").submit();
    }
  });
  
  $("input.use_company").click(function(){
    p_event = $(this).val();
    if($(this).is(':checked')){
      $(p_event + " #event_address").attr("disabled", "disabled");
      $(p_event + " .my_companies").removeClass("hidden");
    }else{
      $(p_event + " #event_address").removeAttr("disabled");
      $(p_event + " .my_companies").addClass("hidden");
    }
  });
  
  function validate_pair(e1, e2){
    result = false;
    if(e1.val() != "" || e2.val() != ""){
      result = true;
    }
    return result;
  }
  
  function validate_fields(element){
    result = true;
    $(element + " span.error").remove();
    require_fields = $(element).find(".required");
    $.each(require_fields, function(){
      if($(this).val()=="" || $(this).val()==null){
        $(this).parent().append("<span class='error'>can't be blank</span>");
        result = false;
      }
    });
    return result;
  }  

app/views/users/new.html.haml
.span
  %p
    %h2 Sign Up
  %br
  ~ form_for @user do |f|
    .errors.span12{style: "margin-bottom: 20px"}
      = render partial: "shared/errors"
    .field.span12
      .span2
        %label Email
      .span4= f.email_field :username
    .field.span12
      .span2
        %label Password
      .span4= f.password_field :password
    .field.span12
      .span2
        %label Password Confirmation
      .span4= password_field_tag :password_confirmation
    .field.span12
      .span1= submit_tag 'Register'