config/routes.rb
StartupShopKC::Application.routes.draw do
  get 'home/index', as: 'home'
  root :to => 'home#index'
  
  get 'search'          => 'home#search', as: 'search'
  post 'search'         => 'home#search', as: 'search'
  get 'update_map'      => 'home#update_map'
  get 'signin'          => 'sessions#new', as: 'signin'
  post 'signin'         => 'sessions#create'
  get 'signout'         => 'sessions#destroy'
  get 'signup'          => 'users#new', as: 'signup'
  get 'my_account'      => 'users#my_account', as: 'my_account'
  get 'charge'          => 'users#charge'
  post 'update_card'    => 'users#update_card'
  get 'locations_by_category' => 'locations#locations_by_category'
  match 'confirm_email/:code' => 'users#confirm_email'
  
  match 'auth/:provider/callback', to: 'sessions#provider'
  match 'auth/failure', to: redirect('/')

  resources :users
  resources :locations
  resources :events
  
  namespace :admin do
    get 'dashboard/index'
    get 'first_admin' => 'dashboard#first_admin', as: 'first_admin'
    post 'create_first_admin' => 'dashboard#create_first_admin', as: 'create_first_admin'
    put 'update_user' => 'dashboard#update_user', as: 'update_user'
    get 'active_location' => 'dashboard#active_location'
    get 'location_filter' => 'dashboard#location_filter'
    get 'active_event' => 'dashboard#active_event'
    get 'event_filter' => 'dashboard#event_filter'
    get 'remove_twitter' => 'dashboard#remove_twitter'
    post 'update_cost' => 'dashboard#update_cost'
    post 'update_twitter' => 'dashboard#update_twitter'
    post 'import_locations' => 'dashboard#import_locations', as: 'import_locations'
    match "/" => "dashboard#index"
    root :to => "admin/dashboard#index"
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @locations = Location.actived_list
    @events = Event.actived_list
    init_news_feed
  end
    
  def search
    if request.post?
      term = params[:term]
      unless term.blank?
        @locations = Location.search(term)
        @events = Event.search(term)
        init_news_feed
        render :index
      else
        redirect_to root_path
      end
    else
      redirect_to root_path
    end
  end
  
  def update_map
    @locations = []
    @locations = Location.where(category: params[:category], active: true)
    @locations = Location.actived_list if params[:category] == 'all'
    points = Point.get_points(@locations, []).to_json
    respond_to do |format|
      format.json { render :json => points }
    end
  end

  private
    def init_news_feed
      @news_feeds = []
      @t_accounts = []
      t_accounts = Setting.where(name: 'twitters').first 
      @t_accounts = t_accounts.svalue.split(',') if t_accounts
      @t_accounts.each do |name|
        @news_feeds += Twitter.user_timeline(name)
      end
    end
end

app/views/home/_add_company.html.haml
#step0_c.inside.hidden
  .progress-bar.step0
  .copy Follow these easy steps to add your Company to StartupShopKC.
  %button(href="#step1_c" class="continue") I'm ready. let's begin!   
#step1_c.inside.hidden
  .progress-bar.step1
  .copy What Category does your company fall into?
  ~ form_tag '', class: 'form' do
    .input
      .label
        %i.icon-list-ul.form-icon
        Category
      .field.select_field
        = select_tag :category, options_for_select(Location::CATEGORIES), class: 'category-select', style: "width: 270px;"
    .input#startup-sub
      .label
        %i.icon-list-ul.form-icon
        Sub-Categories
      .field.select_field
        = select_tag :startup_sub, options_for_select(Location::STARTUP_SUBS), class: 'category-select', style: "width: 270px;"
      
  %button(href="#step2_c" class="continue") Okey! Next step!
#step2_c.inside.hidden
  .progress-bar.step2
  .copy Who Are you and where are you located?
  = render partial: "locations/form"
  %button(href="#step3_c" class="continue") Awesome! What's next?

#step3_c.inside.hidden
  .input
    %p Thank you for your listing, to ensure a community of inspired entrepreneurs the StartupShop team approves every post.  We will let you know when your post goes live.  Doesn't it take us long at all!
    %p In the Mean time tell your friends that you are apart of the Kansas City Startup Community.   
-##step3_c.inside.hidden
  -#.progress-bar.step3
  -#.copy Would you like to highlight your company? It's a great way to get noticed!
  -#%button.continue.no No thanks
  -#%button.continue.yes Yes please!
  
:javascript
  $(document).ready(function(){
    $("select#category").change(function(){
      if($(this).val()=="Startup"){
        $("#startup-sub").removeClass('hidden');
      }else{
        $("#startup-sub").addClass('hidden');
      }
    });
  });

app/views/home/_add_event.html.haml
#step0_e.inside.hidden
  .progress-bar.step0
  .copy Adding your Event to StartupShopKC is extremely easy.
  %button(href="#step1_e" class="continue") I'm ready. let's begin!   
#step1_e.inside.hidden
  .progress-bar.step1
  .copy Next we'll need some important information. Spill it!
  = render partial: 'events/form'
  %button(href="#step2_e" class="continue") Create
#step2_e.inside.hidden
  .input
    %p Thank you for your listing, to ensure a community of inspired entrepreneurs the StartupShop team approves every post.  We will let you know when your post goes live.  Don't it doesn't take us long at all!
    %p In the Mean time tell your friends that you are apart of the Kansas City Startup Community.

app/views/home/_add_something.html.haml
#popover.hidden
  - if current_user
    .background
      .title 
        %span.add-title Add your company or event
        = link_to "<i class='icon-remove-sign title-close-icon'></i>".html_safe, "close"
      #step_choose.inside
        .input
          %p StartupShopKC.com's mission is to help build connections within the Kansas City entrepreneur community through increased awareness of opportunities.
          %p The StartupShopKC.com web portal connects Kansas City startups and enthusiasts with the many resources, events and jobs in the region as well as educational and informational content.
          %p The StartupShop team is passionate about the Kansas City startup scene and is committed to helping build a more vibrant and integrated startup ecosystem. StartupShopKC.com is your destination for discovering Kansas City’s innovation community.
          
        %button(id="add_company" href="#step0_c" class="continue") Add Company
        %button(id="add_event" href="#step0_e" class="continue") Add Event
      #popover_company
        = render partial: 'add_company'
      #popover_event
        = render partial: 'add_event'
  - else
    #popover_login.background
      .title
        %span.add-title Login
        = link_to "<i class='icon-remove-sign title-close-icon'></i>".html_safe, "close"
      .inside
        = render partial: 'shared/login_popup'
        .input
          or
          = link_to "sign up new account", "popover_signup"
    #popover_signup.background.hidden
      .title
        %span.add-title Registration
        = link_to "<i class='icon-remove-sign title-close-icon'></i>".html_safe, "close"
      .inside
        = render partial: 'users/signup'
        .input
          = link_to "login", "popover_login"
:javascript

  $("#popover a[href=close]").click(function(e){
    $("#popover span.add-title").html("Add your company or event");
    $("div[id*=step]").addClass('hidden');
    $("#step_choose").removeClass('hidden');
    $("#popover").addClass('hidden');
    $("#main-menu").removeClass("hidden");
    $(".left-haft-bottom").removeClass("hidden");
    e.preventDefault();
  });
  
  $("a[href=popover_signup]").click(function(e){
    e.preventDefault();
    $("#popover_signup").removeClass("hidden");
    $("#popover_login").addClass("hidden");
  });
  
  $("a[href=popover_login]").click(function(e){
    e.preventDefault();
    $("#popover_login").removeClass("hidden");
    $("#popover_signup").addClass("hidden");
  });
  
  $("button.continue").click(function(e){ 
    next_step = $(this).attr('href');
    if(next_step=="#signin"){
      $("#popover_login form").submit();
    }else if(next_step=="#signup"){
      $("#popover_signup form").submit();
    }else if(next_step=="#step0_c"){
      $('.add-title').text("Add your company");
    }else if(next_step=="#step0_e"){
      $('.add-title').text("Add your event");
    }
    if(next_step=="#step2_c"){
      category = $("#step1_c select#category").val();
      if(category == "Startup"){
        category = $("#step1_c select#startup_sub").val();
      }
      $("#step2_c form").append("<input type='hidden' name='location[category]' value='" + category + "'/>");
      moveToStep(next_step);
    }else if(next_step=="#step3_c"){
      if(validate_fields("#step2_c")==true){
        $("#fading-image").show();
        $("#step2_c form").submit();
      }
    }else if(next_step=="#step2_e"){
      valid_f = validate_fields("#step1_e");
      valid_add = validate_pair($("#event_address"), $("#event_company"));
      if(valid_add==false){
        $("#step1_e .location").append("<div class='label' style='margin-left: 0'><span class='error'>Input address or choose from your companies</span></div>");
      }
      if(valid_f==true && valid_add==true){
        $("#fading-image").show();
        $("#step1_e form").submit();
      }
    }else{
      moveToStep(next_step);
    }
    e.preventDefault();
  });  
  
  function moveToStep(step){
    $("div[id*=step]").addClass('hidden');
    $(step).removeClass('hidden');
  }
  
  $("input#use_company").click(function(){
    if($(this).is(':checked')){
      $("#event_address").attr("disabled", "disabled");
      $("#my_companies").removeClass("hidden");
    }else{
      $("#event_address").removeAttr("disabled");
      $("#my_companies").addClass("hidden");
    }
  });
  
  function validate_pair(e1, e2){
    result = false;
    if(e1.val() != "" || e2.val() != ""){
      result = true;
    }
    return result;
  }
  
  function validate_fields(element){
    result = true;
    $(element + " span.error").remove();
    require_fields = $(element).find(".required");
    $.each(require_fields, function(){
      if($(this).val()=="" || $(this).val()==null){
        $(this).parent().append("<span class='error'>can't be blank</span>");
        result = false;
      }
    });
    return result;
  }  

app/views/home/_category_item.html.haml
= link_to "<i class='#{icon_class} category-icon'></i>".html_safe, update_map_path, rel: cat_name, class: c_class
%span.title= link_to cat_name, update_map_path, rel: cat_name, class: c_class
- if c_class=='parent-menu'
  %span.arrow= link_to "<i class='icon-arrow-down arrow-icon'></i>".html_safe, update_map_path, rel: cat_name, class: c_class
- else
  = link_to "<i class='icon-arrow-right arrow-icon'></i>".html_safe, update_map_path, rel: cat_name, class: c_class

app/views/home/_company_list.html.haml
- locations.each do |loc|
  - logo = loc.logo.blank? ? "/assets/think-big.png" : loc.logo
  - data = {"pos"=> {"lat"=> loc.latitude, "lng"=> loc.longitude}, "name"=> "#{loc.name}", "email"=> "#{loc.email}", "address"=> "#{loc.address}", "id"=> "#{loc.id}", "url"=> "#{loc.url}", "twitter"=> "#{loc.t_user}", "facebook"=> "#{loc.f_user}", "description"=> "#{loc.description}", "logo"=> "#{logo}", "events" => loc.js_events}.to_json
  .category.company
    = link_to "<i class='#{icon_class}'></i>".html_safe, "#", data: data, class: "location_item"
    %span.title= link_to loc.name, "#", data: data, class: "location_item"
    = link_to "<i class='icon-arrow-right arrow-icon'></i>".html_safe, "#", data: data, class: "location_item"
    .info
      .address
        = loc.address
      .city
        = loc.email

app/views/home/_events_menus.html.haml
- @events.each do |event|
  .left-menu.full.slide-out.hidden{id: "event-info_#{event.id}"}
    .background
      .title
        = link_to "<i class='icon-remove-sign title-close-icon'></i>".html_safe, "event-close"
      .inside.inside-full
        .single-company
          .single-company-info.events-info
            %i.icon-pushpin
            %span.title= event.name
            .info-item
              %i.icon-calendar
              %span= event.datetime.strftime("%m/%d%Y")
            .info-item
              %i.icon-time
              %span= event.datetime.strftime("%I:%M %p")
            .info-item
              %i.icon-map-marker
              %span= event.e_address
            .info-item{class: "#{'hidden' if event.phone.blank?}"}
              %i.icon-phone
              %span= event.phone
            .info-item{class: "#{'hidden' if event.email.blank?}"}
              %i.icon-envelope
              %span= event.email
            .info-item{class: "#{'hidden' if(event.url.blank? || event.url=='http://') }"}
              %i.icon-globe
              %span= event.url
          .company-description
            = event.description

#events.left-menu.full.hidden
  .background
    .title 
      = link_to "<i class='icon-arrow-left title-icon'></i>".html_safe, "event-close"   
      %span.title-copy
        Upcoming Events
    .inside.inside-full.events-menu
      %ul.list-events
        - @events.each do |event|
          - data = {"pos"=> {"lat"=> event.latitude, "lng"=> event.longitude}, "name"=> "#{event.name}", "address"=> "#{event.e_address}", "e_time"=> "#{event.e_time}"}.to_json
          %li.c-pointer{id: "#{event.id}", data: data}
            %span
              = event.datetime.strftime("%b")
              %strong= event.datetime.day
            %div
              %strong= event.name
              %small= event.datetime.strftime("%I:%M %p")
:javascript
  $("ul.list-events li").click(function(){
    id = $(this).attr("id");
    $("div[id*=event-info_]").addClass('hidden');
    $("#event-info_" + id).removeClass('hidden');
    data = JSON.parse($(this).attr("data"));
    pos = data.pos;
    latLng = new google.maps.LatLng(pos.lat, pos.lng);
    content1 = "<div class='marker_info'><div class='right close'><a href='#'>x</a></div><div class='info'><h3>" + data.name + "</h3>" + data.e_time + "<br/>" + data.address + "</div></div>";
    content = "<div class='popover'><div class='pop-content'><div class='item-pop head-title-pop'><i class='category_item icon-pushpin'></i><span class='title'>" + data.name + "</span></div><div class='item-pop'><i class='icon-map-marker'></i><span class='title'>" + data.address + "</span></div><div class='item-pop'><i class='icon-time company-info-icon'></i><span>" + data.e_time + "</span></div><span class='arr'></span></div></div>";
    make_overlay(latLng, content, '');      
    $("#mymap").gmap3({action: 'setCenter', args:[latLng]});
    $("#mymap").gmap3('get').setZoom(16);
  });
  
  $("a[href=event-close]").click(function(e){
    $("#events").addClass('hidden');
    $("div[id*=event-info_]").addClass('hidden');
    e.preventDefault();
  });

app/views/home/_locations.html.haml
- @locations.each do |loc|
  - cat = loc.category || 'all'
  .map-location(data-jmapping="{id: '#{loc.id}', point: {lat: #{loc.latitude}, lng: #{loc.longitude}}, category: '#{cat}'}")
    .info-box
      %p= loc.name
      %p= loc.email

app/views/home/_messages.html.haml
#popover
	#popover_login.background
		.title
			%span.add-title Message
			= link_to "<i class='icon-remove-sign title-close-icon'></i>".html_safe, "close"
		.inside
			- flash.each do |name, msg|
				= content_tag :div, msg, :id => "flash_#{name}"